### ISSUE TITLE
weights initialization

### ISSUE THREAD

**Issue by pollytur** [FabianFuchsML/se3-transformer-public#22]
Is their any way to specify the weights initialization strategy during the GSE3Res block creation?

**Comment by FabianFuchsML** [comment]
We don't have anything set up to control initialisation globally, but it's absolutely possible. You will probably need to go into the various modules that are used in the init of `GSE3Res`, such as `G1x1SE3`. There, you can set the initialisation strategy manually. Hope that helps!

**Comment by pollytur** [comment]
Thank you for a fast reply!)
