### ISSUE TITLE
Unit conversion for QM9

### ISSUE THREAD

**Issue by tuanle618** [FabianFuchsML/se3-transformer-public#27]
Hi @FabianFuchsML ,

I want to use the processed dataset provided by your google drive and was wondering what the conversion factors for the
missing target `[cv, A, B, C, u298_atom, h298_atom, g298_atom, u0_atom]` are?
For [`cv, A, B, C]` I believe its the factor `1.0`, but for the `[u298_atom, h298_atom, g298_atom]` it's not clear for me. Is it also the provided `hartree2eV` variable in https://github.com/FabianFuchsML/se3-transformer-public/blob/master/experiments/qm9/QM9.py#L12-L33 ?

All the best,

Tuan

**Comment by FabianFuchsML** [comment]
Hi Tuan,

Yes, it's the Hartree units.

Best wishes!
Fabian

**Comment by tuanle618** [comment]
Hi Fabian, thanks a lot for the quick response! 
I'll adapt (multiply) the `[u298_atom, h298_atom, g298_atom]` targets with the `hartree2eV` variable then.

Best wishes,
Tuan
